{{- if .Values.replication.enabled }}
{{- $service := merge (deepCopy .Values.slave.service) (deepCopy $service) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}-read
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if $service.annotations }}
  annotations: {{- include "postgresql.tplValue" (dict "value" $service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  {{- if and $service.loadBalancerIP (eq $service.type "LoadBalancer") }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq $service.type "LoadBalancer") $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- include "postgresql.tplValue" (dict "value" $service.loadBalancerSourceRanges "context" $) | nindent 4 }}
  {{- end }}
  {{- if and (eq $service.type "ClusterIP") $service.clusterIP }}
  clusterIP: {{ $service.clusterIP }}
  {{- end }}
  ports:
    - name: tcp-postgresql
      port:  {{ template "postgresql.port" . }}
      targetPort: tcp-postgresql
      {{- if $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "postgresql.name" . }}
    release: {{ .Release.Name | quote }}
    role: slave
{{- end }}
